export const ui = {
  chrome: {
    skipToContent: "Skip to content",
    menu: "Menu",
    language: "Language",
    primaryNav: "Primary",
    mobileNav: "Mobile",
    footerNav: "Footer",
    legalNav: "Legal",
  },
  notFound: {
    eyebrow: "404",
    title: "Page not found.",
    body: "Looks like this path doesn't exist.",
    back: "Back to MVPCompanion →",
  },
  contact: {
    directPrefix: "You can also reach us directly at",
    name: "Name",
    email: "Email",
    subject: "Subject",
    optional: "(optional)",
    message: "Message",
    required: "*",
    success: "Thanks — your message has been sent.",
    send: "Send message",
    sending: "Sending…",
    sendFailed: "Something went wrong. Please try again or contact us directly.",
    invalidRequest: "Invalid request.",
    nameError: "Please enter your name (2–120 characters).",
    emailError: "Please enter a valid email address.",
    messageError: "Please enter a message (10–5000 characters).",
    subjectError: "Subject must be 200 characters or fewer.",
  },
  untitledIdea: "Untitled Idea",
  exportMenu: {
    export: "Export",
    json: "Export as JSON",
    pdf: "Export as PDF",
  },
  pdf: {
    heading: "IDEA SNAPSHOT",
    status: "Status",
    clarification: "Clarification",
    clarified: "clarified",
    inProgress: "in progress",
    unresolved: "unresolved",
    currentStage: "Current stage",
    created: "Created",
    updated: "Updated",
    unknownDate: "Unknown",
    snapshotContent: "Snapshot content",
    assumptions: "Recorded assumptions",
    openQuestions: "Open questions",
    footer: "Idea Snapshot",
    statuses: {
      completed: "Completed",
      in_progress: "In progress",
      new: "New",
    },
    stages: {
      intake: "Starting context",
      summary: "Idea Snapshot",
      mvp: "MVPCompanion",
    },
    stageStatus: {
      clarified: "Clarified",
      in_progress: "In progress",
      unresolved: "Unresolved",
    },
  },
  library: {
    heading: "My Ideas",
    viewSnapshot: "View Idea Snapshot",
    newIdea: "+ New Idea",
    importSnapshot: "Import Snapshot",
    empty: "No ideas yet.",
    noHypothesis: "No Idea hypothesis yet.",
    stagePrefix: "Clarification",
    startingContext: "Clarification · Starting context",
    ideaSnapshot: "Clarification · Idea Snapshot",
    updatedRecently: "Updated recently",
    updatedToday: "Updated today",
    updatedYesterday: "Updated yesterday",
    updatedDaysAgo: "Updated {days} days ago",
    currentlyOpen: "Currently open",
    open: "Open",
    delete: "Delete",
    deleteTitle: "Delete this Idea?",
    deleteBody:
      "This will remove the Idea from this browser. Make sure you have exported it if you want to keep a copy.",
    cancel: "Cancel",
    deleteIdea: "Delete Idea",
    importTitle: "Import as a new Idea",
    importBody: "Your existing Ideas will not be changed.",
    idea: "Idea",
    format: "Snapshot format",
    created: "Created",
    updated: "Updated",
    status: "Status",
    progress: "Clarification progress",
    progressValue: "{clarified} clarified · {inProgress} in progress · {unresolved} unresolved",
    availableSections: "Available sections",
    noSections: "No sections clarified yet",
    importNew: "Import as New Idea",
    unknownDate: "Unknown",
    invalidJson: "Invalid JSON file.",
    notSnapshot: "This file is not an MVPCompanion Idea Snapshot.",
    unsupportedVersion: "This Snapshot format version is not supported.",
    malformed: "This Idea Snapshot is malformed.",
  },
  bookPage: {
    eyebrow: "Book",
    primaryReading: "Primary reading",
    experienceHeadline: "Experience how MVPCompanion thinks.",
    experienceBody: "Read the original Preface and Chapter 0 as they appear in the book.",
    readSample: "Read the Sample",
    companionEyebrow: "Companion white paper",
    companionHeadline: "Explore the Method",
    companionBody:
      "Prefer the short version? Read the companion paper for a concise overview of the MVPCompanion method, 15-stage process, five lenses, traceability, learning loop, and human–AI relationship.",
    readPaper: "Read the White Paper",
    metaTitle: "MVPCompanion Book Sample",
  },
  resourcesPage: {
    primarySample: "Primary book sample",
    readSample: "Read the Sample",
    companionEyebrow: "Companion white paper",
    readPaper: "Read the White Paper",
    metaTitle: "Resources — MVPCompanion",
  },
  bookSamplePage: {
    eyebrow: "Book sample",
    title: "Read the Book Sample",
    supporting:
      "Experience the original editorial voice, figures, exercises, and structure of MVPCompanion before Chapter 1 begins.",
    contents: "Book sample contents",
    preface: "Preface",
    chapter: "Chapter 0",
    prefaceDocument: "MVPCompanion Preface — Before You Vibe-Code",
    chapterDocument: "MVPCompanion Chapter 0 — Introduction",
    closingTitle: "Before you vibe-code, vibe-specify.",
    closingBody: "Continue into Chapter 1 when the full book becomes available.",
    metaTitle: "MVPCompanion — Book Sample: Before You Vibe-Code & Chapter 0",
    metaDescription:
      "Read a sample of MVPCompanion, including the Preface ‘Before You Vibe-Code’ and Chapter 0, ‘From an Idea to Something Worth Building.’",
    readOnline: "Read the original document online.",
    openDocument: "Open full document",
    downloadPdf: "Download PDF",
  },
  paperPage: {
    eyebrow: "Companion white paper",
    note: "This condensed methodology overview is a companion white paper, not a book chapter or a substitute for the book sample.",
    documentTitle: "From Idea to MVP — MVPCompanion Short Paper",
    metaTitle: "From Idea to MVP — MVPCompanion Short Paper",
    metaDescription:
      "A concise conceptual and practical overview of the MVPCompanion method, 15-stage process, five lenses, traceability, learning, and human–AI relationship.",
  },
  processPage: {
    also: "See also the",
    homepageLink: "method section on the homepage",
  },
  aboutMetaTitle: "About — MVPCompanion",
  templatesMetaTitle: "Templates — MVPCompanion",
  startMetaTitle: "Clarify your starting point — MVPCompanion",
} as const;
