import type { ProcessPhase, ProcessStage } from "@/content/framework";

export const processStages: readonly ProcessStage[] = [
  {
    number: 1,
    name: "Idee",
    question: "Was könnte das werden?",
    purpose: "Die erste Produktidee fassen.",
    output: "Ideenhypothese / Idea Brief",
  },
  {
    number: 2,
    name: "Problem",
    question: "Welches echte Problem gibt es?",
    purpose: "Das Problem unabhängig von der vorgeschlagenen Lösung beschreiben.",
    output: "Problem Statement plus Belege und Annahmen",
  },
  {
    number: 3,
    name: "Nutzer",
    question: "Wer hat das Problem?",
    purpose: "Die primäre Person benennen, die das Problem hat.",
    output: "Profil der primären Nutzer plus Ziel- und Nicht-Zielsegment",
  },
  {
    number: 4,
    name: "Wert",
    question: "Warum ist die Lösung wichtig?",
    purpose: "Ergebnis und Wert beschreiben, den das Produkt schaffen soll.",
    output: "JTBD plus Wertversprechen, Nutzen, USP und Positionierung",
  },
  {
    number: 5,
    name: "Produkt",
    question: "Was ist das Produkt im Kern?",
    purpose: "Beschreiben, was das Produkt grundsätzlich ist.",
    output: "Mentales Produktmodell plus grobe Entitätenkarte",
  },
  {
    number: 6,
    name: "Kontext",
    question: "Was passiert mit der Hauptsache im Produkt über die Zeit?",
    purpose: "Beschreiben, wie sich das zentrale Objekt des Produkts über die Zeit verändert.",
    output: "Lebenszyklus- / Kontextmodell",
  },
  {
    number: 7,
    name: "Aufgaben",
    question: "Was müssen Nutzer erreichen?",
    purpose: "Benennen, was Nutzer erledigen müssen.",
    output: "Priorisierte Jobs-to-be-Done / zentrale Anwendungsfälle",
  },
  {
    number: 8,
    name: "Umfang",
    question: "Was ist die kleinste nützliche Lösung?",
    purpose: "Die kleinste nützliche Lösung ableiten.",
    output: "MVP-Feature-Karte plus Liste außerhalb des Umfangs",
  },
  {
    number: 9,
    name: "Erlebnis",
    question: "Wie kommt der Nutzer zum Wert?",
    purpose: "Beschreiben, wie der Nutzer zum Wert gelangt.",
    output: "Zentrale Nutzerflüsse plus Screen-Inventar",
  },
  {
    number: 10,
    name: "Informationsarchitektur",
    question: "Wie ist das Produkt organisiert?",
    purpose: "Beschreiben, wie das Produkt aufgebaut ist.",
    output: "Informationsarchitektur plus Navigationsmodell",
  },
  {
    number: 11,
    name: "Daten",
    question: "Welche Entitäten und Felder werden gebraucht?",
    purpose: "Die Daten beschreiben, die das Produkt zum Betrieb braucht.",
    output: "MVP-Entitäten- und Datenmodell",
  },
  {
    number: 12,
    name: "Anforderungen",
    question: "Was genau muss gebaut werden?",
    purpose: "Beschreiben, was gebaut werden muss und wie es sich verhalten soll.",
    output: "Funktionale Anforderungen plus Akzeptanzkriterien",
  },
  {
    number: 13,
    name: "Lernen",
    question: "Woran erkennen wir, dass es funktioniert?",
    purpose: "Beschreiben, was das MVP prüfen und messen muss.",
    output: "Erfolgsmetriken plus Lernfragen",
  },
  {
    number: 14,
    name: "Technische Grenzen",
    question: "Welche technischen Grenzen zählen?",
    purpose: "Technische Einschränkungen und große Risiken beschreiben.",
    output: "Grobarchitektur plus technische Einschränkungen",
  },
  {
    number: 15,
    name: "MVP-Grenze",
    question: "Wo genau hören wir auf?",
    purpose: "Genau festlegen, was ins MVP gehört und was nicht.",
    output: "Umfangsbeschreibung plus priorisierte Feature-Liste plus Ausschlüsse",
  },
];

export const processPhases: readonly ProcessPhase[] = [
  {
    id: "understand",
    number: "01",
    name: "Verstehen",
    purpose: "Verstehen, was gelöst wird und für wen.",
    stageNumbers: [1, 2, 3],
  },
  {
    id: "define",
    number: "02",
    name: "Definieren",
    purpose: "Aus der ersten Idee ein tragfähiges Produktkonzept machen.",
    stageNumbers: [4, 5, 6],
  },
  {
    id: "shape",
    number: "03",
    name: "Gestalten",
    purpose: "Festlegen, was das Produkt tun muss und was es nicht tun muss.",
    stageNumbers: [7, 8, 9],
  },
  {
    id: "specify",
    number: "04",
    name: "Spezifizieren",
    purpose: "Das Produkt konkret genug machen, um es zu entwerfen und zu bauen.",
    stageNumbers: [10, 11, 12],
  },
  {
    id: "learn",
    number: "05",
    name: "Lernen",
    purpose: "Festlegen, was das MVP prüfen muss und wo die Grenze liegt.",
    stageNumbers: [13, 14, 15],
  },
];
