export const ui = {
  chrome: {
    skipToContent: "Zum Inhalt springen",
    menu: "Menü",
    language: "Sprache",
    primaryNav: "Hauptnavigation",
    mobileNav: "Mobil",
    footerNav: "Fußzeile",
    legalNav: "Rechtliches",
  },
  notFound: {
    eyebrow: "404",
    title: "Seite nicht gefunden.",
    body: "Dieser Pfad scheint nicht zu existieren.",
    back: "Zurück zu MVPCompanion →",
  },
  contact: {
    directPrefix: "Sie erreichen uns auch direkt unter",
    name: "Name",
    email: "E-Mail",
    subject: "Betreff",
    optional: "(optional)",
    message: "Nachricht",
    required: "*",
    success: "Danke — Ihre Nachricht wurde gesendet.",
    send: "Nachricht senden",
    sending: "Wird gesendet…",
    sendFailed: "Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut oder schreiben Sie uns direkt.",
    invalidRequest: "Ungültige Anfrage.",
    nameError: "Bitte geben Sie Ihren Namen ein (2–120 Zeichen).",
    emailError: "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
    messageError: "Bitte geben Sie eine Nachricht ein (10–5000 Zeichen).",
    subjectError: "Der Betreff darf höchstens 200 Zeichen lang sein.",
  },
  betaInterest: {
    trigger: "KI-Feedback – Beta",
    fullDraftTrigger: "Interesse an KI-Feedback?",
    title: "KI-Feedback für Ihre MVP-Spezifikation",
    body:
      "Diese Funktion ist noch nicht aktiv. Wir prüfen, ob KI-Feedback Menschen beim Schärfen ihrer MVP-Spezifikation hilft. Ihre Spezifikationstexte werden im Rahmen dieser Umfrage nicht an eine KI gesendet.",
    interestLabel: "Würden Sie KI-Feedback nutzen?",
    interestFree: "Ja, ich würde es kostenlos testen",
    interestPaid: "Ja, ich würde bei gutem Nutzen bezahlen",
    interestNo: "Eher nicht",
    scopeLabel: "Wo wäre Feedback am wertvollsten?",
    scopeClarify: "Klärungsstufen 1–6",
    scopeFull: "Vollständige 15-Stufen-Spezifikation",
    scopeBoth: "Beides",
    priceLabel: "Welcher monatliche Preis wäre für Sie passend?",
    price590: "Bis 5,90 €",
    price990: "Bis 9,90 € für ein höheres Kontingent",
    priceFree: "Nur wenn es kostenlos ist",
    priceUnsure: "Noch unklar",
    emailLabel: "E-Mail für eine Beta-Einladung",
    emailOptional: "optional",
    consentLabel:
      "Ich bin einverstanden, dass MVPCompanion diese E-Mail ausschließlich für eine Kontaktaufnahme zur KI-Feedback-Beta nutzt.",
    privacyPrefix: "Weitere Informationen finden Sie in der ",
    privacyLink: "Datenschutzerklärung",
    submit: "Interesse vormerken",
    submitting: "Wird gesendet…",
    cancel: "Nicht jetzt",
    success: "Vielen Dank. Ihr Feedback wurde vorgemerkt.",
    sendFailed: "Ihr Feedback konnte gerade nicht vorgemerkt werden. Bitte versuchen Sie es später erneut.",
    interestError: "Bitte wählen Sie, ob Sie KI-Feedback nutzen würden.",
    scopeError: "Bitte wählen Sie, wo Feedback am wertvollsten wäre.",
    priceError: "Bitte wählen Sie eine Preispräferenz.",
    emailError: "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
    consentError: "Bitte bestätigen Sie die Einwilligung, bevor Sie eine E-Mail-Adresse absenden.",
  },
  untitledIdea: "Unbenannte Idee",
  exportMenu: {
    export: "Export",
    json: "Als JSON exportieren",
    pdf: "Als PDF exportieren",
    markdown: "Als Markdown exportieren",
    scopeLabel: "Umfang für PDF und Markdown",
    scopeSnapshot: "Ideen-Snapshot (Stufen 1–6)",
    scopeFull: "Gesamter Spezifikationsentwurf (Stufen 1–15)",
    jsonNote: "JSON sichert immer den vollständigen aktiven Entwurf, einschließlich späterer Stufen. Der Umfang ändert seine Feld-IDs nicht.",
  },
  pdf: {
    heading: "IDEEN-SNAPSHOT",
    headingFull: "SPEZIFIKATIONSENTWURF",
    status: "Status",
    clarification: "Klärung",
    clarified: "geklärt",
    inProgress: "in Arbeit",
    unresolved: "offen",
    currentStage: "Aktuelle Phase",
    created: "Erstellt",
    updated: "Aktualisiert",
    exported: "Exportiert",
    unknownDate: "Unbekannt",
    snapshotContent: "Inhalt des Snapshots",
    notValidation: "Ausgefüllte Felder halten fest, was geschrieben wurde. Sie sind keine Marktvalidierung.",
    openContent: "Offen",
    filledField: "Ausgefüllt",
    additionalField: "Zusatzfeld",
    footerFull: "Spezifikationsentwurf",
    assumptions: "Festgehaltene Annahmen",
    openQuestions: "Offene Fragen",
    footer: "Ideen-Snapshot",
    statuses: {
      completed: "Abgeschlossen",
      in_progress: "In Arbeit",
      new: "Neu",
    },
    stages: {
      intake: "Ausgangskontext",
      summary: "Ideen-Snapshot",
      mvp: "MVPCompanion",
    },
    stageStatus: {
      clarified: "Geklärt",
      in_progress: "In Arbeit",
      unresolved: "Offen",
    },
  },
  library: {
    heading: "Meine Ideen",
    viewSnapshot: "Ideen-Snapshot ansehen",
    viewFullSpecification: "Vollständige Spezifikation ansehen",
    newIdea: "+ Neue Idee",
    importSnapshot: "Importieren",
    empty: "Noch keine Ideen.",
    noHypothesis: "Noch keine Ideenhypothese.",
    stagePrefix: "Klärung",
    startingContext: "Klärung · Ausgangskontext",
    ideaSnapshot: "Klärung · Ideen-Snapshot",
    fullSpecification: "Vollständige MVP-Spezifikation",
    updatedRecently: "Kürzlich aktualisiert",
    updatedToday: "Heute aktualisiert",
    updatedYesterday: "Gestern aktualisiert",
    updatedDaysAgo: "Vor {days} Tagen aktualisiert",
    currentlyOpen: "Gerade geöffnet",
    open: "Öffnen",
    delete: "Löschen",
    deleteTitle: "Diese Idee löschen?",
    deleteBody:
      "Die Idee wird aus diesem Browser entfernt. Exportieren Sie sie, wenn Sie eine Kopie behalten möchten.",
    cancel: "Abbrechen",
    deleteIdea: "Idee löschen",
    importTitle: "Entwurf importieren",
    importBody: "Prüfen Sie die Datei, bevor sie hinzugefügt wird. Eine ungültige Datei ändert Ihre Entwürfe nicht.",
    importFullSpecificationTitle: "Vollständige MVP-Spezifikation importieren",
    importFullSpecificationBody:
      "Diese Datei enthält alle 15 Stufen. Sie wird direkt als vollständige Spezifikation geöffnet.",
    importReplaceTitle: "Aktuellen Entwurf ersetzen?",
    importReplaceBody:
      "Diese Datei ersetzt den aktiven Entwurf. Laden Sie vorher eine JSON-Sicherung herunter, wenn Sie ihn behalten möchten. Das Ersetzen können Sie danach rückgängig machen.",
    importFullSpecificationReplaceTitle: "Durch vollständige MVP-Spezifikation ersetzen?",
    importFullSpecificationReplaceBody:
      "Diese 15-Stufen-Datei ersetzt den aktiven Entwurf und wird danach als vollständige Spezifikation geöffnet. Laden Sie vorher eine JSON-Sicherung herunter, wenn Sie den aktuellen Entwurf behalten möchten.",
    importDownload: "JSON-Sicherung herunterladen",
    importReplace: "Entwurf ersetzen",
    undoReplace: "Ersetzen rückgängig machen",
    idea: "Idee",
    format: "Quellformat",
    fileContents: "Dateiinhalt",
    fullSpecificationContents: "15 von 15 Stufen vorhanden",
    created: "Erstellt",
    updated: "Aktualisiert",
    status: "Status",
    progress: "Fortschritt der Klärung",
    progressValue: "{clarified} geklärt · {inProgress} in Arbeit · {unresolved} offen",
    specificationProgress: "Fortschritt der Spezifikation",
    specificationProgressValue: "{filled} von {total} Stufen ausgefüllt",
    availableSections: "Vorhandene Abschnitte",
    includedStages: "Enthaltene Stufen",
    noSections: "Noch keine Abschnitte geklärt",
    importNew: "Als neue Idee importieren",
    importFullSpecification: "Vollständige Spezifikation öffnen",
    importReplaceFullSpecification: "Ersetzen und vollständige Spezifikation öffnen",
    unknownDate: "Unbekannt",
    invalidJson: "Ungültige JSON-Datei.",
    notSnapshot: "Diese Datei ist keine unterstützte MVPCompanion-Importdatei.",
    unsupportedVersion: "Diese Importdatei-Version wird nicht unterstützt.",
    malformed: "Diese MVPCompanion-Importdatei ist fehlerhaft.",
  },
  bookPage: {
    eyebrow: "Buch",
    primaryReading: "Zentrale Lektüre",
    experienceHeadline: "Erleben, wie MVPCompanion denkt.",
    experienceBody: "Lesen Sie Vorwort und Kapitel 0 so, wie sie im Buch stehen.",
    readSample: "Auszug lesen",
    companionEyebrow: "Begleitendes Whitepaper",
    companionHeadline: "Die Methode entdecken",
    companionBody:
      "Lieber die kurze Fassung? Das Begleitpapier gibt einen knappen Überblick über die Methode von MVPCompanion, den Prozess in 15 Phasen, fünf Blickwinkel, Nachvollziehbarkeit, die Lernschleife und das Verhältnis von Mensch und KI.",
    readPaper: "Whitepaper lesen",
    metaTitle: "MVPCompanion Buchauszug",
  },
  resourcesPage: {
    primarySample: "Zentraler Buchauszug",
    readSample: "Auszug lesen",
    companionEyebrow: "Begleitendes Whitepaper",
    readPaper: "Whitepaper lesen",
    processEyebrow: "Prozess in 15 Stufen",
    readProcess: "Prozess lesen",
    metaTitle: "Ressourcen — MVPCompanion",
  },
  bookSamplePage: {
    eyebrow: "Buchauszug",
    title: "Buchauszug lesen",
    supporting:
      "Erleben Sie Stimme, Abbildungen, Übungen und Aufbau von MVPCompanion, bevor Kapitel 1 beginnt.",
    contents: "Inhalt des Buchauszugs",
    preface: "Vorwort",
    chapter: "Kapitel 0",
    prefaceDocument: "MVPCompanion Vorwort — Bevor du Vibe-codest",
    chapterDocument: "MVPCompanion Kapitel 0 — Einleitung",
    closingTitle: "Bevor du Vibe-codest, spezifiziere.",
    closingBody: "Weiter mit Kapitel 1, sobald das vollständige Buch verfügbar ist.",
    metaTitle: "MVPCompanion — Buchauszug: Bevor du Vibe-codest & Kapitel 0",
    metaDescription:
      "Lesen Sie einen Auszug aus MVPCompanion, einschließlich Vorwort und Kapitel 0.",
    readOnline: "Das Originaldokument online lesen.",
    openDocument: "Vollständiges Dokument öffnen",
    downloadPdf: "PDF herunterladen",
  },
  paperPage: {
    eyebrow: "Begleitendes Whitepaper",
    note: "Dieser kompakte Methodenüberblick ist ein begleitendes Whitepaper, kein Buchkapitel und kein Ersatz für den Buchauszug.",
    documentTitle: "Von der Idee zum MVP — Whitepaper von MVPCompanion",
    metaTitle: "Von der Idee zum MVP — Whitepaper von MVPCompanion",
    metaDescription:
      "Ein knapper konzeptioneller und praktischer Überblick über die Methode von MVPCompanion, den Prozess in 15 Phasen, fünf Blickwinkel, Nachvollziehbarkeit, Lernen und das Verhältnis von Mensch und KI.",
  },
  processDocumentPage: {
    eyebrow: "Prozess in 15 Stufen",
    note: "Dieses Dokument ist ein Prozessüberblick über die fünfzehn Stufen. Es ist kein Buchkapitel und kein Ersatz für den Buchauszug.",
    documentTitle: "MVPCompanion — Prozess in 15 Stufen",
    metaTitle: "Prozess in 15 Stufen — MVPCompanion",
    metaDescription:
      "Ein Prozessüberblick über die fünfzehn Stufen der MVPCompanion-Methode, von der Idee zur MVP-Grenze.",
  },
  processPage: {
    also: "Siehe auch den",
    homepageLink: "Methodenabschnitt auf der Startseite",
  },
  aboutMetaTitle: "Über MVPCompanion",
  templatesMetaTitle: "Vorlagen — MVPCompanion",
  startMetaTitle: "Ausgangspunkt klären — MVPCompanion",
} as const;
