export const ui = {
  chrome: {
    skipToContent: "Zum Inhalt springen",
    menu: "Menü",
    language: "Sprache",
    primaryNav: "Hauptnavigation",
    mobileNav: "Mobil",
    footerNav: "Fußzeile",
    legalNav: "Rechtliches",
  },
  notFound: {
    eyebrow: "404",
    title: "Seite nicht gefunden.",
    body: "Dieser Pfad scheint nicht zu existieren.",
    back: "Zurück zu MVPCompanion →",
  },
  contact: {
    directPrefix: "Sie erreichen uns auch direkt unter",
    name: "Name",
    email: "E-Mail",
    subject: "Betreff",
    optional: "(optional)",
    message: "Nachricht",
    required: "*",
    success: "Danke — Ihre Nachricht wurde gesendet.",
    send: "Nachricht senden",
    sending: "Wird gesendet…",
    sendFailed: "Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut oder schreiben Sie uns direkt.",
    invalidRequest: "Ungültige Anfrage.",
    nameError: "Bitte geben Sie Ihren Namen ein (2–120 Zeichen).",
    emailError: "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
    messageError: "Bitte geben Sie eine Nachricht ein (10–5000 Zeichen).",
    subjectError: "Der Betreff darf höchstens 200 Zeichen lang sein.",
  },
  untitledIdea: "Unbenannte Idee",
  exportMenu: {
    export: "Export",
    json: "Als JSON exportieren",
    pdf: "Als PDF exportieren",
  },
  pdf: {
    heading: "IDEEN-SNAPSHOT",
    status: "Status",
    clarification: "Klärung",
    clarified: "geklärt",
    inProgress: "in Arbeit",
    unresolved: "offen",
    currentStage: "Aktuelle Phase",
    created: "Erstellt",
    updated: "Aktualisiert",
    unknownDate: "Unbekannt",
    snapshotContent: "Inhalt des Snapshots",
    assumptions: "Festgehaltene Annahmen",
    openQuestions: "Offene Fragen",
    footer: "Ideen-Snapshot",
    statuses: {
      completed: "Abgeschlossen",
      in_progress: "In Arbeit",
      new: "Neu",
    },
    stages: {
      intake: "Ausgangskontext",
      summary: "Ideen-Snapshot",
      mvp: "MVPCompanion",
    },
    stageStatus: {
      clarified: "Geklärt",
      in_progress: "In Arbeit",
      unresolved: "Offen",
    },
  },
  library: {
    heading: "Meine Ideen",
    viewSnapshot: "Ideen-Snapshot ansehen",
    newIdea: "+ Neue Idee",
    importSnapshot: "Snapshot importieren",
    empty: "Noch keine Ideen.",
    noHypothesis: "Noch keine Ideenhypothese.",
    stagePrefix: "Klärung",
    startingContext: "Klärung · Ausgangskontext",
    ideaSnapshot: "Klärung · Ideen-Snapshot",
    updatedRecently: "Kürzlich aktualisiert",
    updatedToday: "Heute aktualisiert",
    updatedYesterday: "Gestern aktualisiert",
    updatedDaysAgo: "Vor {days} Tagen aktualisiert",
    currentlyOpen: "Gerade geöffnet",
    open: "Öffnen",
    delete: "Löschen",
    deleteTitle: "Diese Idee löschen?",
    deleteBody:
      "Die Idee wird aus diesem Browser entfernt. Exportieren Sie sie, wenn Sie eine Kopie behalten möchten.",
    cancel: "Abbrechen",
    deleteIdea: "Idee löschen",
    importTitle: "Als neue Idee importieren",
    importBody: "Ihre vorhandenen Ideen bleiben unverändert.",
    idea: "Idee",
    format: "Snapshot-Format",
    created: "Erstellt",
    updated: "Aktualisiert",
    status: "Status",
    progress: "Fortschritt der Klärung",
    progressValue: "{clarified} geklärt · {inProgress} in Arbeit · {unresolved} offen",
    availableSections: "Vorhandene Abschnitte",
    noSections: "Noch keine Abschnitte geklärt",
    importNew: "Als neue Idee importieren",
    unknownDate: "Unbekannt",
    invalidJson: "Ungültige JSON-Datei.",
    notSnapshot: "Diese Datei ist kein MVPCompanion-Ideen-Snapshot.",
    unsupportedVersion: "Diese Snapshot-Version wird nicht unterstützt.",
    malformed: "Dieser Ideen-Snapshot ist fehlerhaft.",
  },
  bookPage: {
    eyebrow: "Buch",
    primaryReading: "Zentrale Lektüre",
    experienceHeadline: "Erleben, wie MVPCompanion denkt.",
    experienceBody: "Lesen Sie Vorwort und Kapitel 0 so, wie sie im Buch stehen.",
    readSample: "Auszug lesen",
    companionEyebrow: "Begleitendes Whitepaper",
    companionHeadline: "Die Methode entdecken",
    companionBody:
      "Lieber die kurze Fassung? Das Begleitpapier gibt einen knappen Überblick über die Methode von MVPCompanion, den Prozess in 15 Phasen, fünf Blickwinkel, Nachvollziehbarkeit, die Lernschleife und das Verhältnis von Mensch und KI.",
    readPaper: "Whitepaper lesen",
    metaTitle: "MVPCompanion Buchauszug",
  },
  resourcesPage: {
    primarySample: "Zentraler Buchauszug",
    readSample: "Auszug lesen",
    companionEyebrow: "Begleitendes Whitepaper",
    readPaper: "Whitepaper lesen",
    metaTitle: "Ressourcen — MVPCompanion",
  },
  bookSamplePage: {
    eyebrow: "Buchauszug",
    title: "Buchauszug lesen",
    supporting:
      "Erleben Sie Stimme, Abbildungen, Übungen und Aufbau von MVPCompanion, bevor Kapitel 1 beginnt.",
    contents: "Inhalt des Buchauszugs",
    preface: "Vorwort",
    chapter: "Kapitel 0",
    prefaceDocument: "MVPCompanion Vorwort — Bevor du Vibe-codest",
    chapterDocument: "MVPCompanion Kapitel 0 — Einleitung",
    closingTitle: "Bevor du Vibe-codest, spezifiziere.",
    closingBody: "Weiter mit Kapitel 1, sobald das vollständige Buch verfügbar ist.",
    metaTitle: "MVPCompanion — Buchauszug: Bevor du Vibe-codest & Kapitel 0",
    metaDescription:
      "Lesen Sie einen Auszug aus MVPCompanion, einschließlich Vorwort und Kapitel 0.",
    readOnline: "Das Originaldokument online lesen.",
    openDocument: "Vollständiges Dokument öffnen",
    downloadPdf: "PDF herunterladen",
  },
  paperPage: {
    eyebrow: "Begleitendes Whitepaper",
    note: "Dieser kompakte Methodenüberblick ist ein begleitendes Whitepaper, kein Buchkapitel und kein Ersatz für den Buchauszug.",
    documentTitle: "Von der Idee zum MVP — Whitepaper von MVPCompanion",
    metaTitle: "Von der Idee zum MVP — Whitepaper von MVPCompanion",
    metaDescription:
      "Ein knapper konzeptioneller und praktischer Überblick über die Methode von MVPCompanion, den Prozess in 15 Phasen, fünf Blickwinkel, Nachvollziehbarkeit, Lernen und das Verhältnis von Mensch und KI.",
  },
  processPage: {
    also: "Siehe auch den",
    homepageLink: "Methodenabschnitt auf der Startseite",
  },
  aboutMetaTitle: "Über MVPCompanion",
  templatesMetaTitle: "Vorlagen — MVPCompanion",
  startMetaTitle: "Ausgangspunkt klären — MVPCompanion",
} as const;
